def nv():
	print(' .---.         ')
	print('   (_,/\ \     ')
	print('  (`a a(  )    ')
	print('  ) \=  ) (    ')
	print(' (.--' '--.)   ')
	print(' / (_\_/_) \   ')
	print('| / \   / \ |  ')
	print(' \\ / . \ //   ')
	print('  \/\___/\/    ')
	print('  |  \_/  |    ')
	print('   \  /  /     ')
	print('    \/  /      ')
	print('     ( (       ')
	print('     |\ \      ')
	print('     | \ \     ')
	print('    /_Y/_Y     ')
for i in range(100):
	nv()
	print('\n')
