house = input('房子大小')
area = input('房子面积')
city = input('所在城市')
position = input('详细位置')
price =input('价格')
adviser = input('购物顾问')
print('house%s\narea%s\ncity%s\nposition%s\nprice%s\nadviser%s'%(house,area,city,position,price,adviser))
